WebApplication1/Components/CartCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication1.Controllers;
using WebApplication1.Models;

namespace WebApplication1.Components;

/// <summary>
/// View component that displays the total count of items in the shopping cart.
/// This component is typically used in the layout header to show a real-time cart item count.
/// </summary>
public class CartCountViewComponent : ViewComponent
{
    /// <summary>
    /// Invokes the view component to calculate and return the total cart item count.
    /// </summary>
    /// <returns>A string representation of the total quantity of items in the cart.</returns>
    public IViewComponentResult Invoke()
    {
        // Get the current user session
        var session = HttpContext.Session;
        
        // Retrieve the cart data from session storage using the cart key
        string jsoncart = session.GetString(CartController.CARTKEY);
        
        // Initialize cart count to zero
        int cartCount = 0;
        
        // Check if cart data exists in session
        if (jsoncart != null)
        {
            // Deserialize the JSON string to a list of CartItem objects
            var cart = JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
            
            // Calculate total quantity by summing all item quantities
            // Uses null-coalescing operator to return 0 if cart is null
            cartCount = cart?.Sum(c => c.Quantity) ?? 0;
        }
        
        // Return the cart count as a string content result (return text)
        // Content is a helper method in BaseController/ViewComponent
        return Content(cartCount.ToString());
    }
}

WebApplication1/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.AppData;

namespace WebApplication1.Components;

public class CategoryViewComponent : ViewComponent
{
    private readonly AppDBContext _context;
    
    public CategoryViewComponent(AppDBContext context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categories = await _context.Categories.ToListAsync();
        return View(categories);
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
	<head>
	    <title>Winkel - Free Bootstrap 4 Template by Colorlib</title>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	    
	    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

	    <link rel="stylesheet" href="~/assets/css/open-iconic-bootstrap.min.css">
	    <link rel="stylesheet" href="~/assets/css/animate.css">
	    
	    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
	    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
	    <link rel="stylesheet" href="~/assets/css/magnific-popup.css">

	    <link rel="stylesheet" href="~/assets/css/aos.css">

	    <link rel="stylesheet" href="~/assets/css/ionicons.min.css">

	    <link rel="stylesheet" href="~/assets/css/bootstrap-datepicker.css">
	    <link rel="stylesheet" href="~/assets/css/jquery.timepicker.css">

	    
	    <link rel="stylesheet" href="~/assets/css/flaticon.css">
	    <link rel="stylesheet" href="~/assets/css/icomoon.css">
	    <link rel="stylesheet" href="~/assets/css/style.css">
    	<link rel="stylesheet" href="~/assets/css/cart-custom.css">
    	<link rel="stylesheet" href="~/css/toast.css">
	</head>
	<body class="goto-here">
		<div class="py-1 bg-black">
    		<div class="container">
			    <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
				    <div class="col-lg-12 d-block">
					    <div class="row d-flex">
						    <div class="col-md pr-4 d-flex topper align-items-center">
							    <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
							    <span class="text">+ 1235 2355 98</span>
						    </div>
						    <div class="col-md pr-4 d-flex topper align-items-center">
							    <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
							    <span class="text">youremail@email.com</span>
						    </div>
						    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
							    <span class="text">3-5 Business days delivery &amp; Free Returns</span>
						    </div>
						    <div class="col-md d-flex justify-content-end topper align-items-center text-lg-right">
								@await Html.PartialAsync("_LoginPartial")
						    </div>
					    </div>
					</div>
			    </div>
			</div>
	    </div>
	    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
		    <div class="container">
		      <a class="navbar-brand" asp-controller="Home" asp-action="Index">Winkel</a>
		      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="oi oi-menu"></span> Menu
		      </button>

		      <div class="collapse navbar-collapse" id="ftco-nav">
		        <ul class="navbar-nav ml-auto">
		          <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
		          <li class="nav-item dropdown active">
	              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
	              <div class="dropdown-menu" aria-labelledby="dropdown04">
              		<a class="dropdown-item" asp-controller="Shop" asp-action="Index">Shop</a>
	                @* <a class="dropdown-item" asp-controller="Shop" asp-action="ProductSingle">Single Product</a> *@
	                <a class="dropdown-item" asp-controller="Cart" asp-action="Index">Cart</a>
	                @* <a class="dropdown-item" asp-controller="Checkout" asp-action="Index">Checkout</a> *@
	              </div>
	            </li>
		          <li class="nav-item"><a asp-controller="About" asp-action="Index" class="nav-link">About</a></li>
		          <li class="nav-item"><a asp-controller="Blog" asp-action="Index" class="nav-link">Blog</a></li>
		          <li class="nav-item"><a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a></li>
		          <li class="nav-item cta cta-colored"><a asp-controller="Cart" asp-action="Index" class="nav-link"><span class="icon-shopping_cart"></span>[@await Component.InvokeAsync("CartCount")]</a></li>

		        </ul>
		      </div>
		    </div>
		  </nav>

		@RenderBody()

		<footer class="ftco-footer bg-light ftco-section">
			<div class="container">
				<div class="row">
					<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
				</div>
				<div class="row mb-5">
					<div class="col-md">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Winkel</h2>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
							<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
								<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
								<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
								<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
							</ul>
						</div>
					</div>
					<div class="col-md">
						<div class="ftco-footer-widget mb-4 ml-md-5">
							<h2 class="ftco-heading-2">Menu</h2>
							<ul class="list-unstyled">
								<li><a href="#" class="py-2 d-block">Shop</a></li>
								<li><a href="#" class="py-2 d-block">About</a></li>
								<li><a href="#" class="py-2 d-block">Journal</a></li>
								<li><a href="#" class="py-2 d-block">Contact Us</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-4">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Help</h2>
							<div class="d-flex">
								<ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
									<li><a href="#" class="py-2 d-block">Shipping Information</a></li>
									<li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
									<li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
									<li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
								</ul>
								<ul class="list-unstyled">
									<li><a href="#" class="py-2 d-block">FAQs</a></li>
									<li><a href="#" class="py-2 d-block">Contact</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Have a Questions?</h2>
							<div class="block-23 mb-3">
								<ul>
									<li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
									<li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
									<li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12 text-center">

						<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
					</div>
				</div>
			</div>
		</footer>
		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen">
			<svg class="circular" width="48px" height="48px">
				<circle
					class="path-bg"
					cx="24"
					cy="24"
					r="22"
					fill="none"
					stroke-width="4"
					stroke="#eeeeee"
				/>
				<circle
					class="path"
					cx="24"
					cy="24"
					r="22"
					fill="none"
					stroke-width="4"
					stroke-miterlimit="10"
					stroke="#F96D00"
				/>
			</svg>
		</div>

		<script src="~/assets/js/jquery.min.js"></script>
		<script src="~/assets/js/jquery-migrate-3.0.1.min.js"></script>
		<script src="~/assets/js/popper.min.js"></script>
		<script src="~/assets/js/bootstrap.min.js"></script>
		<script src="~/assets/js/jquery.easing.1.3.js"></script>
		<script src="~/assets/js/jquery.waypoints.min.js"></script>
		<script src="~/assets/js/jquery.stellar.min.js"></script>
		<script src="~/assets/js/owl.carousel.min.js"></script>
		<script src="~/assets/js/jquery.magnific-popup.min.js"></script>
		<script src="~/assets/js/aos.js"></script>
		<script src="~/assets/js/jquery.animateNumber.min.js"></script>
		<script src="~/assets/js/bootstrap-datepicker.js"></script>
		<script src="~/assets/js/scrollax.min.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
		<script src="~/assets/js/google-map.js"></script>
		<script src="~/assets/js/main.js"></script>
		<script src="~/assets/js/cart.js?v=5"></script>
		@RenderSection("Scripts", required: false)
	</body>
</html>

WebApplication1/Views/Shared/_LayoutShop.cshtml
@{
    Layout = "_Layout";
}

<div class="text-center">
    <div class="hero-wrap hero-bread" style="background-image: url('@Url.Content("~/assets/images/bg_6.jpg")');">
        <div class="container">
            <div class="row no-gutters slider-text align-items-center justify-content-center">
                <div class="col-md-9 ftco-animate text-center">
                    <p class="breadcrumbs"> 
                        <span class="mr-2">
                            <a href="index.html">Home</a>
                        </span>
                        <span>Products</span>
                    </p>
    
                    <h1 class="mb-0 bread">Collection Products</h1>
                </div>
            </div>
        </div>
    </div>

    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-10 order-md-last">
                    @RenderBody()   
                </div>

                <div class="col-md-4 col-lg-2 sidebar">
                    @await Component.InvokeAsync("Category")
                </div>
            </div>
        </div>
    </section>
</div>

WebApplication1/Views/Shared/_MinimalLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>@ViewData["Title"] - MyApp</title>

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <link rel="stylesheet" href="~/assets/css/open-iconic-bootstrap.min.css">
        <link rel="stylesheet" href="~/assets/css/animate.css">
	        
        <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
        <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
        <link rel="stylesheet" href="~/assets/css/magnific-popup.css">

        <link rel="stylesheet" href="~/assets/css/aos.css">

        <link rel="stylesheet" href="~/assets/css/ionicons.min.css">

        <link rel="stylesheet" href="~/assets/css/bootstrap-datepicker.css">
        <link rel="stylesheet" href="~/assets/css/jquery.timepicker.css">

	        
        <link rel="stylesheet" href="~/assets/css/flaticon.css">
        <link rel="stylesheet" href="~/assets/css/icomoon.css">
        <link rel="stylesheet" href="~/assets/css/style.css">

        <style>
            body {
                display: flex;
                align-items: center;
                justify-content: center;
                min-height: 100vh;
                background-color: #f8f9fa;
            }
            
            /*.auth-card {*/
            /*    width: 100%;*/
            /*    background: white;*/
            /*    border-radius: 1rem;*/
            /*    box-shadow: 0 4px 20px rgba(0,0,0,0.1);*/
            /*}*/
            
            /*.auth-card h1 {*/
            /*    font-size: 1.8rem;*/
            /*    font-weight: 600;*/
            /*    text-align: center;*/
            /*    margin-bottom: 1.5rem;*/
            /*}*/
        </style>

        @RenderSection("Head", required: false)
    </head>
    <body>
        <main class="auth-card">
            @RenderBody()
        </main>

        <script src="~/assets/js/jquery.min.js"></script>
        <script src="~/assets/js/jquery-migrate-3.0.1.min.js"></script>
        <script src="~/assets/js/popper.min.js"></script>
        <script src="~/assets/js/bootstrap.min.js"></script>
        <script src="~/assets/js/jquery.easing.1.3.js"></script>
        <script src="~/assets/js/jquery.waypoints.min.js"></script>
        <script src="~/assets/js/jquery.stellar.min.js"></script>
        <script src="~/assets/js/owl.carousel.min.js"></script>
        <script src="~/assets/js/jquery.magnific-popup.min.js"></script>
        <script src="~/assets/js/aos.js"></script>
        <script src="~/assets/js/jquery.animateNumber.min.js"></script>
        <script src="~/assets/js/bootstrap-datepicker.js"></script>
        <script src="~/assets/js/scrollax.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
        <script src="~/assets/js/google-map.js"></script>
        <script src="~/assets/js/main.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

WebApplication1/Views/Shared/_NewProducts.cshtml
<section class="ftco-section bg-light">
    	<div class="container">
				<div class="row justify-content-center mb-3 pb-3">
          <div class="col-md-12 heading-section text-center ftco-animate">
            <h2 class="mb-4">Latest Products</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
          </div>
        </div>   		
    	</div>
    	<div class="container">
    		<div class="row">
			    @foreach (var product in ViewBag.LatestProducts)
			    {
				    <div class="col-sm col-md-6 col-lg ftco-animate">
					    <div class="product">
						    <a href="#" class="img-prod"><img class="img-fluid" src="@product.Picture" alt="Colorlib Template">
							    <div class="overlay"></div>
						    </a>
						    <div class="text py-3 px-3">
							    <h3><a href="#">@product.Name</a></h3>
							    <div class="d-flex">
								    <div class="pricing">
									    <p class="price"><span>$@product.Price</span></p>
								    </div>
								    <div class="rating">
									    <p class="text-right">
										    <a href="#"><span class="ion-ios-star-outline"></span></a>
										    <a href="#"><span class="ion-ios-star-outline"></span></a>
										    <a href="#"><span class="ion-ios-star-outline"></span></a>
										    <a href="#"><span class="ion-ios-star-outline"></span></a>
										    <a href="#"><span class="ion-ios-star-outline"></span></a>
									    </p>
								    </div>
							    </div>
							    <p class="bottom-area d-flex px-3">
								    <a href="#" data-product-id="@product.Id" class="add-to-cart text-center py-2 mr-1"><span>Add to cart </span></a>
								    <a href="#" class="buy-now text-center py-2">Buy now</a>
							    </p>
						    </div>
					    </div>
				    </div>  
			    }
    		</div>
    	</div>
    </section>

WebApplication1/Views/Shared/_ProductItem.cshtml
@model WebApplication1.Models.Product

<div class="col-sm-6 col-md-6 col-lg-4 ftco-animate">
    <div class="product">
        <a href="/Product/Detail/@Model.Id" class="img-prod">
            <img class="img-fluid" src="@Model.Picture" alt="@Model.Name">
            <div class="overlay"></div>
        </a>
        <div class="text py-3 px-3">
            <h3><a href="#">@Model.Name</a></h3>
            <div class="d-flex">
                <div class="pricing">
                    <p class="price"><span class="price">$@Model.Price</span></p>
                </div>
                <div class="rating">
                    <p class="text-right">
                        @for (int i = 0; i < 5; i++)
                        {
                            <a href="#"><span class="ion-ios-star-outline"></span></a>
                        }
                    </p>
                </div>
            </div>
            <p class="bottom-area d-flex px-3">
                <a href="#" data-product-id="@Model.Id" class="add-to-cart text-center py-2 mr-1"><span>Add to cart</span></a>
                <a href="#" class="buy-now text-center py-2">Buy now</a>
            </p>
        </div>
    </div>
</div>